baseURL = "https://simonetavoletta.it"
languageCode = "en-us"
title = "Simone Tavoletta"
# https://gohugo.io/getting-started/configuration/#enablegitinfo
enableGitInfo = true

[params]
  homeText = "My Personal Website"
  repo = "https://github.com/skixmix/personal-website"
  gitMainBranch = "trunk"

[menu]
  # layouts/partials/nav.html iterates over .Site.Menus.main
  # https://gohugo.io/content-management/menus/#properties-site-configuration
  [[menu.main]]
    name = "Portfolio"
    pageRef = "/portfolio"
    weight = 2

# https://gohugo.io/getting-started/configuration-markup/#highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    # https://xyproto.github.io/splash/docs/longer/all.html
    style = 'algol_nu'
    tabWidth = 2
  # https://gohugo.io/getting-started/configuration-markup/
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = '../third_party/mononoki/export/'
    target = 'assets'
