name: Build and push to FTP

on:
  push:
    branches:
      - trunk

jobs:
  build-hugo:
    name: Build static site with Hugo
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
          # https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
          set-safe-directory: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.128.2"
          extended: true

      - name: Build Site
        run: |
          git config --global --add safe.directory '*'
          hugo --minify
        working-directory: ./website

      - name: 📂 Sync files on FTP
        # https://github.com/marketplace/actions/ftp-deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          local-dir: ./website/public/ # TODO check
          server-dir: ./personal_website/
