name: Build and push to FTP

on:
  push:
    branches:
      - trunks # TODO: disabled for now

jobs:
  build-hugo:
    name: Build static site with Hugo
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    container:
      # https://hub.docker.com/_/golang
      # Bookworm == Debian 12, stable as of 11/26/23
      image: golang:1.21.4-bookworm

    steps:
      - name: Check out repo
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
          # https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-repositor
          set-safe-directory: true

      - name: Build hugo
        shell: bash -exo pipefail {0}
        working-directory: ./third_party/hugo
        run: |
          git config --global --add safe.directory '*'
          go build .

      - name: Build site
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#custom-shell
        shell: bash -exo pipefail {0}
        working-directory: ./website
        run: |
          git config --global --add safe.directory '*'
          ../third_party/hugo/hugo

      - name: 📂 Sync files on FTP
        # https://github.com/marketplace/actions/ftp-deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{secrets.ftp_username}}
          password: ${{ secrets.ftp_password }}
          local-dir: ./website/public/ # TODO check
          server-dir: ./personal_website/
